project:
  type: website
  output-dir: docs

website:
  title: "Nayab Khurshaidi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Judicial Bias Project.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


